import dns from 'node:dns';
dns.setServers(['8.8.8.8',"8.8.4.4"])


import { Geist, Geist_Mono, Outfit, Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import { Toaster } from 'sonner';
import { Footer } from '@/components/Footer';


const geistRoboto = Outfit({
  subsets: ["latin"],
});



export const metadata = {
  title: "Book Bound",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      data-theme="light"
      lang="en"
      className={`${geistRoboto.className}  h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Navbar></Navbar>
        <main>
          {children}
          <Toaster position="top-center" richColors />
        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
